### PR TITLE
Add sbt_version variable and sbt 1.0 support

### PR DESCRIPTION
**Pull request by gmethvin**

### CODE REVIEW

**Comment by SethTisue** [comment]
giter8 doesn't work with sbt 1 yet, does it?

**Comment by SethTisue** [comment]
sorry, never mind, confusion of levels

a user on #sbt IRC reported a problem with play-java-seed, and I thought this may be the cause, but then I wasn't able to reproduce their problem, so I'm not sure what it was

**Comment by SethTisue** [comment]
oh but what about https://github.com/foundweekends/giter8/issues/336 ? I'm confused

**Comment by 0x6C38** [comment]
https://github.com/playframework/play-scala-starter-example/issues/68

**Pull request merged**
